deploy:
  stage: deploy
  only:
    - master
  script:
    - imagefile=$(nix-build dockerimage.nix)
    - sudo docker rmi -f matrix-dirwatch-nohttp-bot:latest || true
    - sudo docker load < $imagefile
    - sudo docker tag matrix-dirwatch-nohttp-bot:latest $HOST_REGISTRY/matrix-dirwatch-nohttp-bot:latest
    - sudo docker login -u $USER_REGISTRY -p $PW_REGISTRY $HOST_REGISTRY
    - sudo docker push $HOST_REGISTRY/matrix-dirwatch-nohttp-bot:latest
    - nix-build .
    - scp result/bin/matrix-dirwatch-exe $SSH_USER@$HOST_WWW:/root/tools
